### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by wldmr-key** [Geoorool/EventUp#1]
Все классно, но

> Данное программное обеспечение планируется реализовать ...

эта фраза не для ТЗ, а для программы "Время". Правильно: "Приложение следует реализовать..." или (ты же характеризуешь область применения) - "Информационное обеспечение одних и рекламная площадка или маркетплейс для других" - разумеется на более русском языке

Хотел придраться к экономическим преимуществам, но, подумав, не стал

**Comment by id-salnikov** [comment]
[Backlog](https://github.com/Geoorool/EventUp/projects/1)

**Comment by id-salnikov** [comment]
Исправил:
"Приложение следует реализовать в качестве web-сервиса, предоставляющего возможность пользователям коллективной организации мероприятий, а также в качестве платформы для размещения рекламы помещений, участков, площадок и других объектов предназначенных для различного рода событий."

**Comment by wldmr-key** [comment]
нормально, печатай бланк на выполнение курсовой работы и приходи завтра на защиту отчета по практике
